set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_SYSTEM_PROCESSOR Z80)
set(Z80_TOOLCHAIN_DIR "${CMAKE_SOURCE_DIR}/build/_deps/wla-dx-src")
set(ASM_DIALECT "-Z80")

set(CMAKE_C_COMPILER "cl.exe")
set(CMAKE_CXX_COMPILER "cl.exe")

set(TOOLCHAIN_PREFIX ${Z80_TOOLCHAIN_DIR}/wla)
#set linker for ASM
#Linker flags for WLALink can be seen here:https://wla-dx.readthedocs.io/en/latest/wlaflags.html
set(ASM-Z80_LINKER_FLAGS "-d -v -r -S -A" )
set(CMAKE_ASM${ASM_DIALECT}_LINK_EXECUTABLE "${TOOLCHAIN_PREFIX}link.exe <LINK_FLAGS>")
#set compilers for ASM
set(CMAKE_ASM${ASM_DIALECT}_COMPILER_WORKS 1)
set(CMAKE_ASM${ASM_DIALECT}_COMPILER "${TOOLCHAIN_PREFIX}-z80.exe")
set(CMAKE_ASM${ASM_DIALECT}_FLAGS_DEBUG "-D DEBUG")
set(CMAKE_ASM${ASM_DIALECT}_FLAGS_RELEASE "-D RELEASE")


set(CMAKE_FIND_ROOT_PATH ${Z80_TOOLCHAIN_DIR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ASM_DIALECT)
set(Z80_TOOLCHAIN_DIR)

